version: "3.3"
services:
  mongo:
    restart: always
    image: mongo
    container_name: mongo
    volumes: 
      - $HOME/data/db:/data/db:rw
      - $HOME/backups:/backups:rw
      - ./backups.sh:/backups.sh:rwx
      - ./crontab:crontab:rw
    command:
      
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "516489"
